### ISSUE TITLE
[BUG] TuneD no longer working after update to F43

### ISSUE THREAD

**Issue by Humorist2601** [secureblue/secureblue#1586]
### Description

Hello

I was using F42 with GNOME and TuneD use to work alongwith the Quick settings toggle and it use to also change my laptops power mode. However, after update to F43 I can no longer see the quick settings tile or TuneD. Can you tell me how to find the culprit

Thank You

### Reproduce

1. Turn the System On
2. See in Quick Settings

### Expected

There should be Power Modes in the Quick Settings

### Actual

There are no Power Modes in the Quick Settings

### Image

silverblue-nvidia-open-hardened:latest (43.20251105.0)

### Upstream

Yes

### Declaration

- [x] I agree to follow this project's [Code of Conduct](https://secureblue.dev/code-of-conduct).
- [x] I declare that this is not a request for alternate community messaging or social platforms.
- [x] I declare that I have read the [secureblue website](https://secureblue.dev/#about) and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
please provide `systemctl status tuned.service` and `systemctl status tuned-ppd.service`

**Comment by RoyalOughtness** [comment]
also, @Humorist2601 please provide hardware info

**Comment by Humorist2601** [comment]
Hello, sorry for the delay. Here is all the necessary info

### LOGS

`systemctl status tuned.service`
```bash
× tuned.service - Dynamic System Tuning Daemon
     Loaded: loaded (/usr/lib/systemd/system/tuned.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: timeout) since Sat 2025-11-08 01:09:44 PKT; 17min ago
 Invocation: db971469273144b4b48597a5e5a58158
       Docs: man:tuned(8)
             man:tuned.conf(5)
             man:tuned-adm(8)
    Process: 1340 ExecStart=/usr/sbin/tuned -l -P (code=dumped, signal=ABRT)
   Main PID: 1340 (code=dumped, signal=ABRT)
   Mem peak: 53.1M
        CPU: 274ms
```

`systemctl status tuned-ppd.service`
```bash
○ tuned-ppd.service - PPD-to-TuneD API Translation Daemon
     Loaded: loaded (/usr/lib/systemd/system/tuned-ppd.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)
```

### Hardware Info

- Lenovo Legion 5 Pro Gen 6
- secureblue 43
- Linux 6.17.6-300.fc43.x86_64
- GNOME 49.1
- 11th Gen Intel(R) Core(TM) i7-11800H

**Comment by RoyalOughtness** [comment]
@Humorist2601 please provide


`journalctl -u tuned.service` and the same for tuned-ppd.service 

(run those as root)

**Comment by Humorist2601** [comment]
<details>
  <summary>journalctl -u tuned.service</summary>

  ```bash
Nov 05 23:46:42 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 05 23:46:42 secureblue systemd[1]: Started tuned.service - Dynamic System Tuning Daemon.
Nov 05 23:48:22 secureblue systemd[1]: Stopping tuned.service - Dynamic System Tuning Daemon...
Nov 05 23:48:22 secureblue systemd[1]: tuned.service: Deactivated successfully.
Nov 05 23:48:22 secureblue systemd[1]: Stopped tuned.service - Dynamic System Tuning Daemon.
-- Boot 3f620906e28647e3ae7248e442fd7125 --
Nov 05 23:49:07 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 05 23:49:07 secureblue systemd[1]: Started tuned.service - Dynamic System Tuning Daemon.
-- Boot 19dd139b31a24929bfc182690ceeeedf --
Nov 05 23:53:50 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 05 23:54:35 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 05 23:55:21 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 05 23:55:21 secureblue systemd[1]: tuned.service: Killing process 1471 (tuned) with signal SIGABRT.
Nov 05 23:55:21 secureblue systemd[1]: tuned.service: Main process exited, code=dumped, status=6/ABRT
Nov 05 23:55:21 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 05 23:55:21 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
-- Boot 7ebae897afc147eab6cdd0abbc416e43 --
Nov 05 23:58:58 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 05 23:59:43 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 06 00:00:28 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 06 00:00:28 secureblue systemd[1]: tuned.service: Killing process 1467 (tuned) with signal SIGABRT.
Nov 06 00:00:28 secureblue systemd[1]: tuned.service: Main process exited, code=dumped, status=6/ABRT
Nov 06 00:00:28 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 06 00:00:28 secureblue systemd[1]: Stopped tuned.service - Dynamic System Tuning Daemon.
-- Boot e7ae86934f9a43289b093ebe7dadd2c5 --
Nov 06 14:50:03 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 06 14:50:46 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 06 14:51:31 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 06 14:51:31 secureblue systemd[1]: tuned.service: Killing process 1471 (tuned) with signal SIGABRT.
Nov 06 14:51:31 secureblue systemd[1]: tuned.service: Main process exited, code=dumped, status=6/ABRT
Nov 06 14:51:31 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 06 14:51:31 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
Nov 06 15:00:27 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 06 15:01:12 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 06 15:01:58 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 06 15:01:58 secureblue systemd[1]: tuned.service: Killing process 11145 (tuned) with signal SIGABRT.
Nov 06 15:02:43 secureblue systemd[1]: tuned.service: State 'stop-watchdog' timed out. Killing.
Nov 06 15:02:43 secureblue systemd[1]: tuned.service: Killing process 11145 (tuned) with signal SIGKILL.
Nov 06 15:03:28 secureblue systemd[1]: tuned.service: Processes still around after SIGKILL. Ignoring.
Nov 06 15:04:13 secureblue systemd[1]: tuned.service: State 'final-sigterm' timed out. Aborting.
Nov 06 15:04:13 secureblue systemd[1]: tuned.service: Killing process 11145 (tuned) with signal SIGABRT.
Nov 06 15:04:59 secureblue systemd[1]: tuned.service: State 'final-watchdog' timed out. Killing.
Nov 06 15:04:59 secureblue systemd[1]: tuned.service: Killing process 11145 (tuned) with signal SIGKILL.
Nov 06 15:05:44 secureblue systemd[1]: tuned.service: Processes still around after final SIGKILL. Entering failed mode.
Nov 06 15:05:44 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 06 15:05:44 secureblue systemd[1]: tuned.service: Unit process 11145 (tuned) remains running after unit stopped.
Nov 06 15:05:44 secureblue systemd[1]: Stopped tuned.service - Dynamic System Tuning Daemon.
Nov 06 15:05:44 secureblue systemd[1]: tuned.service: Found left-over process 11145 (tuned) in control group while starting unit. Ignoring.
Nov 06 15:05:44 secureblue systemd[1]: tuned.service: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Nov 06 15:05:44 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 06 15:06:29 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 06 15:07:14 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 06 15:07:14 secureblue systemd[1]: tuned.service: Killing process 12376 (tuned) with signal SIGABRT.
Nov 06 15:07:14 secureblue systemd[1]: tuned.service: Killing process 11145 (tuned) with signal SIGABRT.
Nov 06 15:08:00 secureblue systemd[1]: tuned.service: State 'stop-watchdog' timed out. Killing.
Nov 06 15:08:00 secureblue systemd[1]: tuned.service: Killing process 12376 (tuned) with signal SIGKILL.
Nov 06 15:08:00 secureblue systemd[1]: tuned.service: Killing process 11145 (tuned) with signal SIGKILL.
Nov 06 15:08:45 secureblue systemd[1]: tuned.service: Processes still around after SIGKILL. Ignoring.
Nov 06 15:09:30 secureblue systemd[1]: tuned.service: State 'final-sigterm' timed out. Aborting.
Nov 06 15:09:30 secureblue systemd[1]: tuned.service: Killing process 12376 (tuned) with signal SIGABRT.
Nov 06 15:09:30 secureblue systemd[1]: tuned.service: Killing process 11145 (tuned) with signal SIGABRT.
Nov 06 15:10:15 secureblue systemd[1]: tuned.service: State 'final-watchdog' timed out. Killing.
Nov 06 15:10:15 secureblue systemd[1]: tuned.service: Killing process 12376 (tuned) with signal SIGKILL.
Nov 06 15:10:15 secureblue systemd[1]: tuned.service: Killing process 11145 (tuned) with signal SIGKILL.
Nov 06 15:11:00 secureblue systemd[1]: tuned.service: Processes still around after final SIGKILL. Entering failed mode.
Nov 06 15:11:00 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 06 15:11:00 secureblue systemd[1]: tuned.service: Unit process 11145 (tuned) remains running after unit stopped.
Nov 06 15:11:00 secureblue systemd[1]: tuned.service: Unit process 12376 (tuned) remains running after unit stopped.
Nov 06 15:11:00 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
Nov 06 15:11:00 secureblue systemd[1]: tuned.service: Consumed 449ms CPU time, 90.3M memory peak.
-- Boot 05c1555640da44d9933887501d578b3a --
Nov 06 18:22:45 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 06 18:23:30 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 06 18:24:15 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 06 18:24:15 secureblue systemd[1]: tuned.service: Killing process 1475 (tuned) with signal SIGABRT.
Nov 06 18:24:15 secureblue systemd[1]: tuned.service: Main process exited, code=dumped, status=6/ABRT
Nov 06 18:24:15 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 06 18:24:15 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
-- Boot 44a3d0415016411fbaffa6019dab89c1 --
Nov 06 19:55:03 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 06 19:55:48 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 06 19:56:33 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 06 19:56:33 secureblue systemd[1]: tuned.service: Killing process 1776 (tuned) with signal SIGABRT.
Nov 06 19:56:33 secureblue systemd[1]: tuned.service: Main process exited, code=dumped, status=6/ABRT
Nov 06 19:56:33 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 06 19:56:33 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
-- Boot 9ac46e87e36446e184581840540d9d50 --
Nov 06 20:43:52 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 06 20:44:37 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 06 20:45:22 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 06 20:45:22 secureblue systemd[1]: tuned.service: Killing process 1353 (tuned) with signal SIGABRT.
Nov 06 20:45:22 secureblue systemd[1]: tuned.service: Main process exited, code=dumped, status=6/ABRT
Nov 06 20:45:22 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 06 20:45:22 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
Nov 06 20:49:13 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 06 20:49:59 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 06 20:50:44 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 06 20:50:44 secureblue systemd[1]: tuned.service: Killing process 7153 (tuned) with signal SIGABRT.
Nov 06 20:51:29 secureblue systemd[1]: tuned.service: State 'stop-watchdog' timed out. Killing.
Nov 06 20:51:29 secureblue systemd[1]: tuned.service: Killing process 7153 (tuned) with signal SIGKILL.
Nov 06 20:52:14 secureblue systemd[1]: tuned.service: Processes still around after SIGKILL. Ignoring.
Nov 06 20:53:00 secureblue systemd[1]: tuned.service: State 'final-sigterm' timed out. Aborting.
Nov 06 20:53:00 secureblue systemd[1]: tuned.service: Killing process 7153 (tuned) with signal SIGABRT.
Nov 06 20:53:45 secureblue systemd[1]: tuned.service: State 'final-watchdog' timed out. Killing.
Nov 06 20:53:45 secureblue systemd[1]: tuned.service: Killing process 7153 (tuned) with signal SIGKILL.
Nov 06 20:54:30 secureblue systemd[1]: tuned.service: Processes still around after final SIGKILL. Entering failed mode.
Nov 06 20:54:30 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 06 20:54:30 secureblue systemd[1]: tuned.service: Unit process 7153 (tuned) remains running after unit stopped.
Nov 06 20:54:30 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
Nov 06 20:55:09 secureblue systemd[1]: tuned.service: Found left-over process 7153 (tuned) in control group while starting unit. Ignoring.
Nov 06 20:55:09 secureblue systemd[1]: tuned.service: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Nov 06 20:55:09 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 06 20:55:54 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 06 20:56:39 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 06 20:56:39 secureblue systemd[1]: tuned.service: Killing process 8692 (tuned) with signal SIGABRT.
Nov 06 20:56:39 secureblue systemd[1]: tuned.service: Killing process 7153 (tuned) with signal SIGABRT.
Nov 06 20:57:24 secureblue systemd[1]: tuned.service: State 'stop-watchdog' timed out. Killing.
Nov 06 20:57:24 secureblue systemd[1]: tuned.service: Killing process 8692 (tuned) with signal SIGKILL.
Nov 06 20:57:24 secureblue systemd[1]: tuned.service: Killing process 7153 (tuned) with signal SIGKILL.
Nov 06 20:58:10 secureblue systemd[1]: tuned.service: Processes still around after SIGKILL. Ignoring.
Nov 06 20:58:55 secureblue systemd[1]: tuned.service: State 'final-sigterm' timed out. Aborting.
Nov 06 20:58:55 secureblue systemd[1]: tuned.service: Killing process 8692 (tuned) with signal SIGABRT.
Nov 06 20:58:55 secureblue systemd[1]: tuned.service: Killing process 7153 (tuned) with signal SIGABRT.
Nov 06 20:59:40 secureblue systemd[1]: tuned.service: State 'final-watchdog' timed out. Killing.
Nov 06 20:59:40 secureblue systemd[1]: tuned.service: Killing process 8692 (tuned) with signal SIGKILL.
Nov 06 20:59:40 secureblue systemd[1]: tuned.service: Killing process 7153 (tuned) with signal SIGKILL.
Nov 06 21:00:25 secureblue systemd[1]: tuned.service: Processes still around after final SIGKILL. Entering failed mode.
Nov 06 21:00:25 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 06 21:00:25 secureblue systemd[1]: tuned.service: Unit process 7153 (tuned) remains running after unit stopped.
Nov 06 21:00:25 secureblue systemd[1]: tuned.service: Unit process 8692 (tuned) remains running after unit stopped.
Nov 06 21:00:25 secureblue systemd[1]: Stopped tuned.service - Dynamic System Tuning Daemon.
Nov 06 21:00:25 secureblue systemd[1]: tuned.service: Consumed 427ms CPU time, 90.6M memory peak.
Nov 06 21:00:25 secureblue systemd[1]: tuned.service: Found left-over process 7153 (tuned) in control group while starting unit. Ignoring.
Nov 06 21:00:25 secureblue systemd[1]: tuned.service: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Nov 06 21:00:25 secureblue systemd[1]: tuned.service: Found left-over process 8692 (tuned) in control group while starting unit. Ignoring.
Nov 06 21:00:25 secureblue systemd[1]: tuned.service: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Nov 06 21:00:25 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 06 21:01:11 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 06 21:01:56 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 06 21:01:56 secureblue systemd[1]: tuned.service: Killing process 9750 (tuned) with signal SIGABRT.
Nov 06 21:01:56 secureblue systemd[1]: tuned.service: Killing process 7153 (tuned) with signal SIGABRT.
Nov 06 21:01:56 secureblue systemd[1]: tuned.service: Killing process 8692 (tuned) with signal SIGABRT.
Nov 06 21:02:41 secureblue systemd[1]: tuned.service: State 'stop-watchdog' timed out. Killing.
Nov 06 21:02:41 secureblue systemd[1]: tuned.service: Killing process 9750 (tuned) with signal SIGKILL.
Nov 06 21:02:41 secureblue systemd[1]: tuned.service: Killing process 7153 (tuned) with signal SIGKILL.
Nov 06 21:02:41 secureblue systemd[1]: tuned.service: Killing process 8692 (tuned) with signal SIGKILL.
Nov 06 21:03:26 secureblue systemd[1]: tuned.service: Processes still around after SIGKILL. Ignoring.
Nov 06 21:04:11 secureblue systemd[1]: tuned.service: State 'final-sigterm' timed out. Aborting.
Nov 06 21:04:11 secureblue systemd[1]: tuned.service: Killing process 9750 (tuned) with signal SIGABRT.
Nov 06 21:04:11 secureblue systemd[1]: tuned.service: Killing process 7153 (tuned) with signal SIGABRT.
Nov 06 21:04:11 secureblue systemd[1]: tuned.service: Killing process 8692 (tuned) with signal SIGABRT.
Nov 06 21:04:57 secureblue systemd[1]: tuned.service: State 'final-watchdog' timed out. Killing.
Nov 06 21:04:57 secureblue systemd[1]: tuned.service: Killing process 9750 (tuned) with signal SIGKILL.
Nov 06 21:04:57 secureblue systemd[1]: tuned.service: Killing process 7153 (tuned) with signal SIGKILL.
Nov 06 21:04:57 secureblue systemd[1]: tuned.service: Killing process 8692 (tuned) with signal SIGKILL.
Nov 06 21:05:42 secureblue systemd[1]: tuned.service: Processes still around after final SIGKILL. Entering failed mode.
Nov 06 21:05:42 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 06 21:05:42 secureblue systemd[1]: tuned.service: Unit process 7153 (tuned) remains running after unit stopped.
Nov 06 21:05:42 secureblue systemd[1]: tuned.service: Unit process 8692 (tuned) remains running after unit stopped.
Nov 06 21:05:42 secureblue systemd[1]: tuned.service: Unit process 9750 (tuned) remains running after unit stopped.
Nov 06 21:05:42 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
Nov 06 21:05:42 secureblue systemd[1]: tuned.service: Consumed 440ms CPU time, 136.1M memory peak.
-- Boot c3175e3bf005409c98432d93cf59ad06 --
Nov 07 21:33:23 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 07 21:34:08 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 07 21:34:54 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 07 21:34:54 secureblue systemd[1]: tuned.service: Killing process 1351 (tuned) with signal SIGABRT.
Nov 07 21:34:54 secureblue systemd[1]: tuned.service: Main process exited, code=dumped, status=6/ABRT
Nov 07 21:34:54 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 07 21:34:54 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
-- Boot 70113f7d20b241bd8ba21adaba32347b --
Nov 07 21:49:55 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 07 21:50:40 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 07 21:51:25 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 07 21:51:25 secureblue systemd[1]: tuned.service: Killing process 1351 (tuned) with signal SIGABRT.
Nov 07 21:51:25 secureblue systemd[1]: tuned.service: Main process exited, code=dumped, status=6/ABRT
Nov 07 21:51:25 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 07 21:51:25 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
Nov 07 22:25:20 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 07 22:26:05 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 07 22:26:50 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 07 22:26:50 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGABRT.
Nov 07 22:27:35 secureblue systemd[1]: tuned.service: State 'stop-watchdog' timed out. Killing.
Nov 07 22:27:35 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGKILL.
Nov 07 22:28:21 secureblue systemd[1]: tuned.service: Processes still around after SIGKILL. Ignoring.
Nov 07 22:29:06 secureblue systemd[1]: tuned.service: State 'final-sigterm' timed out. Aborting.
Nov 07 22:29:06 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGABRT.
Nov 07 22:29:51 secureblue systemd[1]: tuned.service: State 'final-watchdog' timed out. Killing.
Nov 07 22:29:51 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGKILL.
Nov 07 22:30:36 secureblue systemd[1]: tuned.service: Processes still around after final SIGKILL. Entering failed mode.
Nov 07 22:30:36 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 07 22:30:36 secureblue systemd[1]: tuned.service: Unit process 144553 (tuned) remains running after unit stopped.
Nov 07 22:30:36 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
Nov 07 22:33:31 secureblue systemd[1]: tuned.service: Found left-over process 144553 (tuned) in control group while starting unit. Ignoring.
Nov 07 22:33:31 secureblue systemd[1]: tuned.service: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Nov 07 22:33:31 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 07 22:34:16 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 07 22:35:02 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 07 22:35:02 secureblue systemd[1]: tuned.service: Killing process 155712 (tuned) with signal SIGABRT.
Nov 07 22:35:02 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGABRT.
Nov 07 22:35:47 secureblue systemd[1]: tuned.service: State 'stop-watchdog' timed out. Killing.
Nov 07 22:35:47 secureblue systemd[1]: tuned.service: Killing process 155712 (tuned) with signal SIGKILL.
Nov 07 22:35:47 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGKILL.
Nov 07 22:36:32 secureblue systemd[1]: tuned.service: Processes still around after SIGKILL. Ignoring.
Nov 07 22:37:17 secureblue systemd[1]: tuned.service: State 'final-sigterm' timed out. Aborting.
Nov 07 22:37:17 secureblue systemd[1]: tuned.service: Killing process 155712 (tuned) with signal SIGABRT.
Nov 07 22:37:17 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGABRT.
Nov 07 22:38:03 secureblue systemd[1]: tuned.service: State 'final-watchdog' timed out. Killing.
Nov 07 22:38:03 secureblue systemd[1]: tuned.service: Killing process 155712 (tuned) with signal SIGKILL.
Nov 07 22:38:03 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGKILL.
Nov 07 22:38:48 secureblue systemd[1]: tuned.service: Processes still around after final SIGKILL. Entering failed mode.
Nov 07 22:38:48 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 07 22:38:48 secureblue systemd[1]: tuned.service: Unit process 144553 (tuned) remains running after unit stopped.
Nov 07 22:38:48 secureblue systemd[1]: tuned.service: Unit process 155712 (tuned) remains running after unit stopped.
Nov 07 22:38:48 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
Nov 07 22:38:48 secureblue systemd[1]: tuned.service: Consumed 429ms CPU time, 90.1M memory peak.
Nov 07 22:42:09 secureblue systemd[1]: tuned.service: Found left-over process 144553 (tuned) in control group while starting unit. Ignoring.
Nov 07 22:42:09 secureblue systemd[1]: tuned.service: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Nov 07 22:42:09 secureblue systemd[1]: tuned.service: Found left-over process 155712 (tuned) in control group while starting unit. Ignoring.
Nov 07 22:42:09 secureblue systemd[1]: tuned.service: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Nov 07 22:42:09 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 07 22:42:54 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 07 22:43:39 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 07 22:43:39 secureblue systemd[1]: tuned.service: Killing process 166219 (tuned) with signal SIGABRT.
Nov 07 22:43:39 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGABRT.
Nov 07 22:43:39 secureblue systemd[1]: tuned.service: Killing process 155712 (tuned) with signal SIGABRT.
Nov 07 22:44:24 secureblue systemd[1]: tuned.service: State 'stop-watchdog' timed out. Killing.
Nov 07 22:44:24 secureblue systemd[1]: tuned.service: Killing process 166219 (tuned) with signal SIGKILL.
Nov 07 22:44:24 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGKILL.
Nov 07 22:44:24 secureblue systemd[1]: tuned.service: Killing process 155712 (tuned) with signal SIGKILL.
Nov 07 22:45:09 secureblue systemd[1]: tuned.service: Processes still around after SIGKILL. Ignoring.
Nov 07 22:45:55 secureblue systemd[1]: tuned.service: State 'final-sigterm' timed out. Aborting.
Nov 07 22:45:55 secureblue systemd[1]: tuned.service: Killing process 166219 (tuned) with signal SIGABRT.
Nov 07 22:45:55 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGABRT.
Nov 07 22:45:55 secureblue systemd[1]: tuned.service: Killing process 155712 (tuned) with signal SIGABRT.
Nov 07 22:46:40 secureblue systemd[1]: tuned.service: State 'final-watchdog' timed out. Killing.
Nov 07 22:46:40 secureblue systemd[1]: tuned.service: Killing process 166219 (tuned) with signal SIGKILL.
Nov 07 22:46:40 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGKILL.
Nov 07 22:46:40 secureblue systemd[1]: tuned.service: Killing process 155712 (tuned) with signal SIGKILL.
Nov 07 22:47:25 secureblue systemd[1]: tuned.service: Processes still around after final SIGKILL. Entering failed mode.
Nov 07 22:47:25 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 07 22:47:25 secureblue systemd[1]: tuned.service: Unit process 144553 (tuned) remains running after unit stopped.
Nov 07 22:47:25 secureblue systemd[1]: tuned.service: Unit process 155712 (tuned) remains running after unit stopped.
Nov 07 22:47:25 secureblue systemd[1]: tuned.service: Unit process 166219 (tuned) remains running after unit stopped.
Nov 07 22:47:25 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
Nov 07 22:47:25 secureblue systemd[1]: tuned.service: Consumed 431ms CPU time, 135.2M memory peak.
Nov 07 23:16:07 secureblue systemd[1]: tuned.service: Found left-over process 144553 (tuned) in control group while starting unit. Ignoring.
Nov 07 23:16:07 secureblue systemd[1]: tuned.service: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Nov 07 23:16:07 secureblue systemd[1]: tuned.service: Found left-over process 155712 (tuned) in control group while starting unit. Ignoring.
Nov 07 23:16:07 secureblue systemd[1]: tuned.service: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Nov 07 23:16:07 secureblue systemd[1]: tuned.service: Found left-over process 166219 (tuned) in control group while starting unit. Ignoring.
Nov 07 23:16:07 secureblue systemd[1]: tuned.service: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Nov 07 23:16:07 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 07 23:16:52 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 07 23:17:37 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 07 23:17:37 secureblue systemd[1]: tuned.service: Killing process 191203 (tuned) with signal SIGABRT.
Nov 07 23:17:37 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGABRT.
Nov 07 23:17:37 secureblue systemd[1]: tuned.service: Killing process 155712 (tuned) with signal SIGABRT.
Nov 07 23:17:37 secureblue systemd[1]: tuned.service: Killing process 166219 (tuned) with signal SIGABRT.
Nov 07 23:18:22 secureblue systemd[1]: tuned.service: State 'stop-watchdog' timed out. Killing.
Nov 07 23:18:22 secureblue systemd[1]: tuned.service: Killing process 191203 (tuned) with signal SIGKILL.
Nov 07 23:18:22 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGKILL.
Nov 07 23:18:22 secureblue systemd[1]: tuned.service: Killing process 155712 (tuned) with signal SIGKILL.
Nov 07 23:18:22 secureblue systemd[1]: tuned.service: Killing process 166219 (tuned) with signal SIGKILL.
Nov 07 23:19:07 secureblue systemd[1]: tuned.service: Processes still around after SIGKILL. Ignoring.
Nov 07 23:19:53 secureblue systemd[1]: tuned.service: State 'final-sigterm' timed out. Aborting.
Nov 07 23:19:53 secureblue systemd[1]: tuned.service: Killing process 191203 (tuned) with signal SIGABRT.
Nov 07 23:19:53 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGABRT.
Nov 07 23:19:53 secureblue systemd[1]: tuned.service: Killing process 155712 (tuned) with signal SIGABRT.
Nov 07 23:19:53 secureblue systemd[1]: tuned.service: Killing process 166219 (tuned) with signal SIGABRT.
Nov 07 23:20:38 secureblue systemd[1]: tuned.service: State 'final-watchdog' timed out. Killing.
Nov 07 23:20:38 secureblue systemd[1]: tuned.service: Killing process 191203 (tuned) with signal SIGKILL.
Nov 07 23:20:38 secureblue systemd[1]: tuned.service: Killing process 144553 (tuned) with signal SIGKILL.
Nov 07 23:20:38 secureblue systemd[1]: tuned.service: Killing process 155712 (tuned) with signal SIGKILL.
Nov 07 23:20:38 secureblue systemd[1]: tuned.service: Killing process 166219 (tuned) with signal SIGKILL.
Nov 07 23:21:23 secureblue systemd[1]: tuned.service: Processes still around after final SIGKILL. Entering failed mode.
Nov 07 23:21:23 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 07 23:21:23 secureblue systemd[1]: tuned.service: Unit process 144553 (tuned) remains running after unit stopped.
Nov 07 23:21:23 secureblue systemd[1]: tuned.service: Unit process 155712 (tuned) remains running after unit stopped.
Nov 07 23:21:23 secureblue systemd[1]: tuned.service: Unit process 166219 (tuned) remains running after unit stopped.
Nov 07 23:21:23 secureblue systemd[1]: tuned.service: Unit process 191203 (tuned) remains running after unit stopped.
Nov 07 23:21:23 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
Nov 07 23:21:23 secureblue systemd[1]: tuned.service: Consumed 430ms CPU time, 179.9M memory peak.
-- Boot 806587342f184aff9fd4a3bd82bf1115 --
Nov 08 00:24:41 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 08 00:25:26 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 08 00:26:11 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 08 00:26:11 secureblue systemd[1]: tuned.service: Killing process 1338 (tuned) with signal SIGABRT.
Nov 08 00:26:11 secureblue systemd[1]: tuned.service: Main process exited, code=dumped, status=6/ABRT
Nov 08 00:26:11 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 08 00:26:11 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
Nov 08 00:46:09 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 08 00:46:54 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 08 00:47:40 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 08 00:47:40 secureblue systemd[1]: tuned.service: Killing process 18402 (tuned) with signal SIGABRT.
Nov 08 00:48:53 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 08 00:48:53 secureblue systemd[1]: tuned.service: Killing process 18402 (tuned) with signal SIGABRT.
Nov 08 00:49:38 secureblue systemd[1]: tuned.service: State 'stop-watchdog' timed out. Killing.
Nov 08 00:49:38 secureblue systemd[1]: tuned.service: Killing process 18402 (tuned) with signal SIGKILL.
Nov 08 00:50:23 secureblue systemd[1]: tuned.service: Processes still around after SIGKILL. Ignoring.
Nov 08 00:51:08 secureblue systemd[1]: tuned.service: State 'final-sigterm' timed out. Aborting.
Nov 08 00:51:08 secureblue systemd[1]: tuned.service: Killing process 18402 (tuned) with signal SIGABRT.
Nov 08 00:51:53 secureblue systemd[1]: tuned.service: State 'final-watchdog' timed out. Killing.
Nov 08 00:51:53 secureblue systemd[1]: tuned.service: Killing process 18402 (tuned) with signal SIGKILL.
Nov 08 00:52:39 secureblue systemd[1]: tuned.service: Processes still around after final SIGKILL. Entering failed mode.
Nov 08 00:52:39 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 08 00:52:39 secureblue systemd[1]: tuned.service: Unit process 18402 (tuned) remains running after unit stopped.
Nov 08 00:52:39 secureblue systemd[1]: Stopped tuned.service - Dynamic System Tuning Daemon.
-- Boot 11a0ae678a97465f872db2a45e0a723a --
Nov 08 00:54:49 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 08 00:55:34 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 08 00:56:19 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 08 00:56:19 secureblue systemd[1]: tuned.service: Killing process 1335 (tuned) with signal SIGABRT.
Nov 08 00:56:19 secureblue systemd[1]: tuned.service: Main process exited, code=dumped, status=6/ABRT
Nov 08 00:56:19 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 08 00:56:19 secureblue systemd[1]: Stopped tuned.service - Dynamic System Tuning Daemon.
-- Boot 6db6491112614b8f9ad9ddeba9085217 --
Nov 08 01:08:14 secureblue systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
Nov 08 01:08:59 secureblue systemd[1]: tuned.service: start operation timed out. Terminating.
Nov 08 01:09:44 secureblue systemd[1]: tuned.service: State 'stop-sigterm' timed out. Aborting.
Nov 08 01:09:44 secureblue systemd[1]: tuned.service: Killing process 1340 (tuned) with signal SIGABRT.
Nov 08 01:09:44 secureblue systemd[1]: tuned.service: Main process exited, code=dumped, status=6/ABRT
Nov 08 01:09:44 secureblue systemd[1]: tuned.service: Failed with result 'timeout'.
Nov 08 01:09:44 secureblue systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
  ```
</details>

<details>
  <summary>journalctl -u tuned-ppd.service</summary>

  ```bash
Nov 05 23:46:42 secureblue systemd[1]: Starting tuned-ppd.service - PPD-to-TuneD API Translation Daemon...
Nov 05 23:46:42 secureblue systemd[1]: Started tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 05 23:48:22 secureblue systemd[1]: Stopping tuned-ppd.service - PPD-to-TuneD API Translation Daemon...
Nov 05 23:48:22 secureblue systemd[1]: tuned-ppd.service: Deactivated successfully.
Nov 05 23:48:22 secureblue systemd[1]: Stopped tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
-- Boot 3f620906e28647e3ae7248e442fd7125 --
Nov 05 23:49:07 secureblue systemd[1]: Starting tuned-ppd.service - PPD-to-TuneD API Translation Daemon...
Nov 05 23:49:07 secureblue systemd[1]: Started tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 05 23:50:18 secureblue systemd[1]: Stopping tuned-ppd.service - PPD-to-TuneD API Translation Daemon...
Nov 05 23:51:03 secureblue systemd[1]: tuned-ppd.service: State 'stop-sigterm' timed out. Aborting.
Nov 05 23:51:03 secureblue systemd[1]: tuned-ppd.service: Killing process 1536 (tuned-ppd) with signal SIGABRT.
Nov 05 23:51:48 secureblue systemd[1]: tuned-ppd.service: State 'stop-watchdog' timed out. Killing.
Nov 05 23:51:48 secureblue systemd[1]: tuned-ppd.service: Killing process 1536 (tuned-ppd) with signal SIGKILL.
Nov 05 23:52:33 secureblue systemd[1]: tuned-ppd.service: Processes still around after SIGKILL. Ignoring.
-- Boot 19dd139b31a24929bfc182690ceeeedf --
Nov 05 23:55:21 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 05 23:55:21 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
-- Boot e7ae86934f9a43289b093ebe7dadd2c5 --
Nov 06 14:51:31 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 06 14:51:31 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
Nov 06 15:11:00 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 06 15:11:00 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
-- Boot 05c1555640da44d9933887501d578b3a --
Nov 06 18:24:15 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 06 18:24:15 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
-- Boot 44a3d0415016411fbaffa6019dab89c1 --
Nov 06 19:56:33 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 06 19:56:33 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
-- Boot 9ac46e87e36446e184581840540d9d50 --
Nov 06 20:45:22 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 06 20:45:22 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
Nov 06 21:05:42 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 06 21:05:42 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
-- Boot c3175e3bf005409c98432d93cf59ad06 --
Nov 07 21:34:54 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 07 21:34:54 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
-- Boot 70113f7d20b241bd8ba21adaba32347b --
Nov 07 21:51:25 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 07 21:51:25 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
Nov 07 22:30:36 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 07 22:30:36 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
Nov 07 22:38:48 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 07 22:38:48 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
Nov 07 22:47:25 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 07 22:47:25 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
Nov 07 23:21:23 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 07 23:21:23 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
-- Boot 806587342f184aff9fd4a3bd82bf1115 --
Nov 08 00:26:11 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 08 00:26:11 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
-- Boot 6db6491112614b8f9ad9ddeba9085217 --
Nov 08 01:09:44 secureblue systemd[1]: Dependency failed for tuned-ppd.service - PPD-to-TuneD API Translation Daemon.
Nov 08 01:09:44 secureblue systemd[1]: tuned-ppd.service: Job tuned-ppd.service/start failed with result 'dependency'.
  ```
</details>

**Comment by RoyalOughtness** [comment]
@Humorist2601 interesting, there's one other person seeing this issue on discord

**Comment by Humorist2601** [comment]
Any debugging you need from my side?

**Comment by mr-r0bot-86** [comment]
I'll add that the same issue occurs on image:
cosmic-main-hardened

**Comment by RoyalOughtness** [comment]
This should be resolved by kernel 6.17.9 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/cpufreq/intel_pstate.c?h=linux-6.17.y&id=63e2dfb59b1a8001ba9307b8bd3fb17199428ac0

**Comment by RoyalOughtness** [comment]
@mr-r0bot-86 @Humorist2601 FYI, I was able to reproduce this. Removing our kargs fixed it, but then adding the kargs back, I couldn't reproduce... Very strange.

**Comment by icenoctua** [comment]
Hello everyone!

I confirm the problem is still present on the latest image. TuneD fails to start, which results in missing Power Profiles in GNOME Quick Settings.

Details:

Image: silverblue-main-hardened:latest, 43.20260205.0

Model and CPU:  Thinkpad, i7-8565U

Kernel: 6.18.8-200.fc43.x86_64

`systemctl status tuned.service`
```× tuned.service - Dynamic System Tuning Daemon
     Loaded: loaded (/usr/lib/systemd/system/tuned.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: timeout) since Fri 2026-02-06 11:28:37 CET; 36min ago
 Invocation: cf77dc04d1cd41d08bf583c7cd70310b
       Docs: man:tuned(8)
             man:tuned.conf(5)
             man:tuned-adm(8)
    Process: 1203 ExecStart=/usr/sbin/tuned -l -P (code=dumped, signal=ABRT)
   Main PID: 1203 (code=dumped, signal=ABRT)
   Mem peak: 50.5M
        CPU: 402ms
```

`systemctl status tuned-ppd.service`

```
○ tuned-ppd.service - PPD-to-TuneD API Translation Daemon
     Loaded: loaded (/usr/lib/systemd/system/tuned-ppd.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)
```

Additional Info: I tried to run TuneD manually using run0 /usr/sbin/tuned -v -P and it exits immediately with exit code 203 and no output. tuned-adm commands also fail with: Cannot talk to TuneD daemon via DBus.

Should I remove kargs and then add them back? How eventually can I do that?

Thank you!!

**Comment by helinoscool** [comment]
I can not replicate this:
```
● tuned.service - Dynamic System Tuning Daemon
     Loaded: loaded (/usr/lib/systemd/system/tuned.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Mon 2026-09-21 09:19:30 CEST; 28min ago
 Invocation: d75e62b0aa074a15aa996f0daf539cbb
       Docs: man:tuned(8)
             man:tuned.conf(5)
             man:tuned-adm(8)
   Main PID: 1222 (tuned)
      Tasks: 4 (limit: 18499)
     Memory: 698.4M (peak: 732.3M)
        CPU: 3.013s
     CGroup: /system.slice/tuned.service
             └─1222 /usr/bin/python3 -Es /usr/sbin/tuned -l -P

Warning: some journal files were not opened due to insufficient permissions.

● tuned-ppd.service - PPD-to-TuneD API Translation Daemon
     Loaded: loaded (/usr/lib/systemd/system/tuned-ppd.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Mon 2026-09-21 09:19:31 CEST; 29min ago
 Invocation: b93a4357a905490cbd2d6e737b9e39d8
   Main PID: 1326 (tuned-ppd)
      Tasks: 4 (limit: 18499)
     Memory: 39.5M (peak: 40.7M)
        CPU: 481ms
     CGroup: /system.slice/tuned-ppd.service
             └─1326 /usr/bin/python3 -Es /usr/sbin/tuned-ppd -l

```
